//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан вручную по образцу ResXFileCodeGenerator.
//     Настройки <TreatWarningsAsErrors> не применяются к этому файлу.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable
#pragma warning disable 1591

namespace KeyboardTester.UI.Resources
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    /// Строго типизированный класс ресурсов для поиска локализованных строк и т.д.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Strings()
        {
        }

        /// <summary>
        /// Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "KeyboardTester.UI.Resources.Strings",
                        typeof(Strings).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Переопределяет свойство CurrentUICulture текущего потока для всех
        /// обращений к ресурсам с помощью этого класса ресурсов со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);

        public static string Error => ResourceManager.GetString("Error", resourceCulture);

        public static string UnexpectedError => ResourceManager.GetString("UnexpectedError", resourceCulture);

        public static string OpenLinkFailed => ResourceManager.GetString("OpenLinkFailed", resourceCulture);

        public static string StartTest => ResourceManager.GetString("StartTest", resourceCulture);

        public static string StopTest => ResourceManager.GetString("StopTest", resourceCulture);

        public static string ResetTest => ResourceManager.GetString("ResetTest", resourceCulture);

        public static string GhostingTest => ResourceManager.GetString("GhostingTest", resourceCulture);

        public static string GhostingTestStop => ResourceManager.GetString("GhostingTestStop", resourceCulture);

        public static string Settings => ResourceManager.GetString("Settings", resourceCulture);

        public static string About => ResourceManager.GetString("About", resourceCulture);

        public static string Layout => ResourceManager.GetString("Layout", resourceCulture);

        public static string Keyboard => ResourceManager.GetString("Keyboard", resourceCulture);

        public static string KeyboardFallback => ResourceManager.GetString("KeyboardFallback", resourceCulture);

        public static string Duration => ResourceManager.GetString("Duration", resourceCulture);

        public static string TotalPresses => ResourceManager.GetString("TotalPresses", resourceCulture);

        public static string ProblematicKeys => ResourceManager.GetString("ProblematicKeys", resourceCulture);

        public static string TabCharts => ResourceManager.GetString("TabCharts", resourceCulture);

        public static string TabGhosting => ResourceManager.GetString("TabGhosting", resourceCulture);

        public static string TabStatistics => ResourceManager.GetString("TabStatistics", resourceCulture);

        public static string TabHistory => ResourceManager.GetString("TabHistory", resourceCulture);

        public static string ColumnKey => ResourceManager.GetString("ColumnKey", resourceCulture);

        public static string ColumnPressCount => ResourceManager.GetString("ColumnPressCount", resourceCulture);

        public static string ColumnAvgInterval => ResourceManager.GetString("ColumnAvgInterval", resourceCulture);

        public static string ColumnAvgHold => ResourceManager.GetString("ColumnAvgHold", resourceCulture);

        public static string ColumnChatter => ResourceManager.GetString("ColumnChatter", resourceCulture);

        public static string ColumnStatus => ResourceManager.GetString("ColumnStatus", resourceCulture);

        public static string FilterAll => ResourceManager.GetString("FilterAll", resourceCulture);

        public static string FilterProblematic => ResourceManager.GetString("FilterProblematic", resourceCulture);

        public static string FilterNotTested => ResourceManager.GetString("FilterNotTested", resourceCulture);

        public static string StatusNotTested => ResourceManager.GetString("StatusNotTested", resourceCulture);

        public static string StatusOk => ResourceManager.GetString("StatusOk", resourceCulture);

        public static string StatusWarning => ResourceManager.GetString("StatusWarning", resourceCulture);

        public static string StatusCritical => ResourceManager.GetString("StatusCritical", resourceCulture);

        public static string TooltipPressCount => ResourceManager.GetString("TooltipPressCount", resourceCulture);

        public static string TooltipStatus => ResourceManager.GetString("TooltipStatus", resourceCulture);

        public static string IntervalChartTitle => ResourceManager.GetString("IntervalChartTitle", resourceCulture);

        public static string HoldChartTitle => ResourceManager.GetString("HoldChartTitle", resourceCulture);

        public static string IntervalSeriesName => ResourceManager.GetString("IntervalSeriesName", resourceCulture);

        public static string HoldSeriesName => ResourceManager.GetString("HoldSeriesName", resourceCulture);

        public static string NoData => ResourceManager.GetString("NoData", resourceCulture);

        public static string SelectKeyHint => ResourceManager.GetString("SelectKeyHint", resourceCulture);

        public static string GhostingInstruction => ResourceManager.GetString("GhostingInstruction", resourceCulture);

        public static string GhostingPressed => ResourceManager.GetString("GhostingPressed", resourceCulture);

        public static string GhostingMax => ResourceManager.GetString("GhostingMax", resourceCulture);

        public static string NKRO => ResourceManager.GetString("NKRO", resourceCulture);

        public static string NKRODetected => ResourceManager.GetString("NKRODetected", resourceCulture);

        public static string SixKRODetected => ResourceManager.GetString("SixKRODetected", resourceCulture);

        public static string ColumnName => ResourceManager.GetString("ColumnName", resourceCulture);

        public static string ColumnDate => ResourceManager.GetString("ColumnDate", resourceCulture);

        public static string ColumnDuration => ResourceManager.GetString("ColumnDuration", resourceCulture);

        public static string ColumnPresses => ResourceManager.GetString("ColumnPresses", resourceCulture);

        public static string ColumnProblematic => ResourceManager.GetString("ColumnProblematic", resourceCulture);

        public static string SaveCurrentSession => ResourceManager.GetString("SaveCurrentSession", resourceCulture);

        public static string Delete => ResourceManager.GetString("Delete", resourceCulture);

        public static string CompareLastTwo => ResourceManager.GetString("CompareLastTwo", resourceCulture);

        public static string CompareSessions => ResourceManager.GetString("CompareSessions", resourceCulture);

        public static string ComparisonTitle => ResourceManager.GetString("ComparisonTitle", resourceCulture);

        public static string ComparisonPressDelta => ResourceManager.GetString("ComparisonPressDelta", resourceCulture);

        public static string ComparisonProblematicDelta => ResourceManager.GetString("ComparisonProblematicDelta", resourceCulture);

        public static string ComparisonStatusChanges => ResourceManager.GetString("ComparisonStatusChanges", resourceCulture);

        public static string ConfirmDeleteTitle => ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);

        public static string ConfirmDelete => ResourceManager.GetString("ConfirmDelete", resourceCulture);

        public static string SessionSaved => ResourceManager.GetString("SessionSaved", resourceCulture);

        public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture);

        public static string ThresholdCritical => ResourceManager.GetString("ThresholdCritical", resourceCulture);

        public static string ThresholdWarning => ResourceManager.GetString("ThresholdWarning", resourceCulture);

        public static string ThresholdMild => ResourceManager.GetString("ThresholdMild", resourceCulture);

        public static string ThresholdStuck => ResourceManager.GetString("ThresholdStuck", resourceCulture);

        public static string MaxEvents => ResourceManager.GetString("MaxEvents", resourceCulture);

        public static string Theme => ResourceManager.GetString("Theme", resourceCulture);

        public static string ThemeSystem => ResourceManager.GetString("ThemeSystem", resourceCulture);

        public static string ThemeDark => ResourceManager.GetString("ThemeDark", resourceCulture);

        public static string ThemeLight => ResourceManager.GetString("ThemeLight", resourceCulture);

        public static string SettingsRestartHint => ResourceManager.GetString("SettingsRestartHint", resourceCulture);

        public static string Save => ResourceManager.GetString("Save", resourceCulture);

        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);

        public static string InvalidSettingsTitle => ResourceManager.GetString("InvalidSettingsTitle", resourceCulture);

        public static string InvalidSettingsPositive => ResourceManager.GetString("InvalidSettingsPositive", resourceCulture);

        public static string InvalidSettingsThresholdOrder => ResourceManager.GetString("InvalidSettingsThresholdOrder", resourceCulture);

        public static string AboutTitle => ResourceManager.GetString("AboutTitle", resourceCulture);

        public static string AboutDescription => ResourceManager.GetString("AboutDescription", resourceCulture);

        public static string Version => ResourceManager.GetString("Version", resourceCulture);

        public static string VersionUnknown => ResourceManager.GetString("VersionUnknown", resourceCulture);

        public static string Repository => ResourceManager.GetString("Repository", resourceCulture);

        public static string GitHubLink => ResourceManager.GetString("GitHubLink", resourceCulture);

        public static string License => ResourceManager.GetString("License", resourceCulture);

        public static string UsedLibraries => ResourceManager.GetString("UsedLibraries", resourceCulture);

        public static string UsedLibrariesList => ResourceManager.GetString("UsedLibrariesList", resourceCulture);

        public static string CheckUpdates => ResourceManager.GetString("CheckUpdates", resourceCulture);

        public static string Close => ResourceManager.GetString("Close", resourceCulture);
    }
}
